# Generated by Django 5.2.5 on 2026-01-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalationevent',
            name='assigned_agent',
            field=models.CharField(blank=True, null=True),
        ),
    ]
