# Generated by Django 5.2.12 on 2026-03-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_escalationevent_assigned_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='notes',
            field=models.CharField(blank=True, null=True),
        ),
    ]
