# Generated by Django 5.2.5 on 2026-01-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_plan_billing_cycle_subscription_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='billing_cycle',
        ),
        migrations.AddField(
            model_name='plan',
            name='price_discount',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=5),
        ),
        migrations.AddField(
            model_name='subscription',
            name='amount_payable',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20),
        ),
    ]
