# Generated by Django 5.2.5 on 2026-01-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_plan_billing_cycle_plan_price_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='features',
            field=models.TextField(),
        ),
    ]
