# Generated by Django 5.2.5 on 2026-01-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_plan_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='price_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
