# Generated by Django 5.2.5 on 2026-01-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_plan_price_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='price_discount',
            field=models.IntegerField(default=0),
        ),
    ]
