# Generated by Django 5.2.5 on 2026-01-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_email_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
