# Generated by Django 5.2.5 on 2026-01-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tenant_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
