# Generated by Django 5.2.12 on 2026-03-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Dan', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Danny', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='staff_ID',
            field=models.CharField(default='AAA111', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='dan@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
