# Generated by Django 5.2.5 on 2026-01-10 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_tenant_whatsapp_number'),
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_first_response_seconds', models.IntegerField(default=120)),
                ('max_human_takeover_seconds', models.IntegerField(default=300)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='SLAViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(max_length=50)),
                ('seconds_late', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='DailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('leads_received', models.IntegerField(default=0)),
                ('leads_qualified', models.IntegerField(default=0)),
                ('leads_booked', models.IntegerField(default=0)),
                ('avg_first_response_seconds', models.IntegerField(default=0)),
                ('avg_time_to_booking_seconds', models.IntegerField(default=0)),
                ('ai_only_conversions', models.IntegerField(default=0)),
                ('human_assisted_conversions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'date')},
            },
        ),
    ]
