# Generated by Django 5.2.5 on 2026-01-29 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailymetrics',
            options={'ordering': ['-date']},
        ),
    ]
